Full Stack Developer/Ruby on Rails/Project Rails App/config/routes.rb
Rails.application.routes.draw do
  
  resources :posts do
  	resources :comments
  end

  root 'pages#index', as: 'home'

  get 'about' => 'pages#about', as: 'about'
  get 'services' => 'pages#services', as: 'services'
  get 'contact' => 'pages#contact', as: 'contact'
end

Full Stack Developer/Ruby on Rails/Project Rails App/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

Full Stack Developer/Ruby on Rails/Project Rails App/app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
	validates :title, presence: true,
						length: {minimum: 5}
end

Full Stack Developer/Ruby on Rails/Project Rails App/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Full Stack Developer/Ruby on Rails/Project Rails App/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: "brad", password: "1234", only: [:destroy]

  def create
  	@post = Post.find(params[:post_id])
  	@comment = @post.comments.create(comment_params)
  	redirect_to post_path(@post)
  end

  def destroy
  	@post = Post.find(params[:post_id])
  	@comment = @post.comments.find(params[:id])
  	@comment.destroy
  	redirect_to post_path(@post)
  end

  private 
  def comment_params
  	params.require(:comment).permit(:username, :body)
  end
end

Full Stack Developer/Ruby on Rails/Project Rails App/app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
		@title = 'Welcome'
		@content = 'Welcome To the homepage'
	end

	def about
		@title = 'About'
		@content = 'Welcome To the about page'
	end

	def services
		@title = 'Services'
		@content = 'Welcome To the services page'
		@services = ['Web Design', 'Web Development', 'SEO']
	end

	def contact
		@title = 'Welcome'
		@content = 'Contact us at..'
	end
end

Full Stack Developer/Ruby on Rails/Project Rails App/app/controllers/posts_controller.rb
class PostsController < ApplicationController
http_basic_authenticate_with name: "brad", password: "1234", except: [:index, :show]
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    #render plain: params[:post].inspect
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else 
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else 
      render 'edit'
    end

  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  private
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

Full Stack Developer/Ruby on Rails/Project Rails App/app/helpers/application_helper.rb
module ApplicationHelper
end

Full Stack Developer/Ruby on Rails/Project Rails App/app/helpers/comments_helper.rb
module CommentsHelper
end

Full Stack Developer/Ruby on Rails/Project Rails App/app/helpers/pages_helper.rb
module PagesHelper
end

Full Stack Developer/Ruby on Rails/Project Rails App/app/helpers/posts_helper.rb
module PostsHelper
end

Full Stack Developer/Ruby on Rails/Project Rails App/app/views/comments/_comments.html.erb
<h3>Comments</h3>
<% @post.comments.each do |comment| %>
	<div class="well">
	<p><strong><%= comment.username %>: </strong><%= comment.body %> <%= link_to '[X]', [comment.post, comment],
					method: :delete,
					data: {confirm: 'Are you sure?'} %></p>
	</div>
<% end %>

Full Stack Developer/Ruby on Rails/Project Rails App/app/views/comments/_form.html.erb
<h3>Add Comment</h3>
<%= form_for([@post, @post.comments.build]) do |f| %>
	<div class="form-group">
		<%= f.label:username %><br>
		<%= f.text_field(:username, {:class => 'form-control'}) %>
	</div>
	<div class="form-group">
		<%= f.label:body %><br>
		<%= f.text_area(:body, {:class => 'form-control'}) %>
	</div>
	<p>
	<%= f.submit({:class => 'btn btn-primary'}) %>
	</p>
<% end %>

Full Stack Developer/Ruby on Rails/Project Rails App/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railsapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">RailsApp</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", home_path %></li>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Services", services_path %></li>
            <li><%= link_to "Blog", posts_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Create Post", new_post_path %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div><!-- /.container -->

</body>
</html>

Full Stack Developer/Ruby on Rails/Project Rails App/app/views/pages/about.html.erb
<%= render 'pages/partials/content' %>

Full Stack Developer/Ruby on Rails/Project Rails App/app/views/pages/contact.html.erb
<%= render 'pages/partials/content' %>

Full Stack Developer/Ruby on Rails/Project Rails App/app/views/pages/index.html.erb
<%= render 'pages/partials/content' %>

Full Stack Developer/Ruby on Rails/Project Rails App/app/views/pages/partials/_content.html.erb
<h1><%= @title %></h1>
<p><%= @content %></p>

Full Stack Developer/Ruby on Rails/Project Rails App/app/views/pages/services.html.erb
<%= render 'pages/partials/content' %>

<% for @service in @services %>
	<div class="well">
		<%= @service %>
	</div>
<% end %>

Full Stack Developer/Ruby on Rails/Project Rails App/app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<% @post.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>
	<div class="form-group">
		<%= f.label:title %><br>
		<%= f.text_field(:title, {:class => 'form-control'}) %>
	</div>
	<div class="form-group">
		<%= f.label:body %><br>
		<%= f.text_area(:body, {:class => 'form-control'}) %>
	</div>
	<p>
	<%= f.submit({:class => 'btn btn-primary'}) %>
	</p>
<% end %>

Full Stack Developer/Ruby on Rails/Project Rails App/app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render 'form' %>

Full Stack Developer/Ruby on Rails/Project Rails App/app/views/posts/index.html.erb
<h1>Latest Blog Posts</h1>
<% @posts.each do |post| %>
	<div class="well">
	<h3><%= post.title %></h3>
	<p><%= post.body %></p>
	<%= link_to 'Read More', post_path(post), :class => 'btn btn-default' %>
	</div>
<% end %>

Full Stack Developer/Ruby on Rails/Project Rails App/app/views/posts/new.html.erb
<h1>Create Post</h1>
<%= render 'form' %>

Full Stack Developer/Ruby on Rails/Project Rails App/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>
<hr>
<%= link_to 'Edit', edit_post_path(@post), :class => 'btn btn-default' %>
<%= link_to 'Delete', post_path(@post), 
						method: :delete,
						data: {confirm: 'Are You Sure?'},
						:class => 'btn btn-danger' %>


<%= render 'comments/comments' %>
<%= render 'comments/form' %>